package com.joaoepedro.tasks

data class Lang(
    val tabToday: String, val tabFamily: String, val tabTasks: String,
    val tabMissions: String, val tabBalance: String, val tabConfig: String,
    val headerSubtitle: String,
    val sectionToday: String, val noActiveTasks: String, val labelNow: String,
    val labelPeriodicity: String, val labelNextChange: String, val btnSwapTasks: String,
    val noPersonAssigned: String,
    val sectionFamily: String, val noPeople: String, val yearsOld: String,
    val sectionTasks: String, val labelOrder: String, val labelNextEvent: String,
    val labelManualAdjust: String, val btnAssociatePerson: String, val btnRemovePerson: String,
    val sectionMissions: String, val noMissions: String,
    val labelRewardPerParticipant: String, val labelParticipants: String,
    val noPhases: String, val noParticipants: String,
    val statusCompleted: String, val statusReady: String, val statusInProgress: String,
    val btnAddPhase: String, val btnCompleteCredit: String, val btnDeleteMission: String,
    val sectionRewards: String, val labelBalance: String,
    val tapForStatement: String, val btnAddBalance: String, val btnWithdraw: String, val btnPenalize: String,
    val titleStatement: String, val labelCurrentBalance: String, val labelMovements: String,
    val noMovements: String, val btnReversePenalty: String, val labelReversed: String,
    val sectionConfig: String,
    val cardPointValue: String, val pointValueDesc: String,
    val cardDailyAllowance: String, val statusDisabled: String, val statusEnabledSince: String,
    val cardBackup: String, val backupDesc: String, val btnGenerateBackup: String, val btnRestoreBackup: String,
    val cardSummary: String, val labelPeople: String, val labelActivities: String, val labelTransactions: String,
    val cardLanguage: String, val titleLanguage: String,
    val cardBiometric: String, val biometricOn: String, val biometricOff: String,
    val biometricTitle: String, val biometricSubtitle: String, val biometricCancel: String,
    val biometricNotAvailable: String, val btnEnableBiometric: String, val btnDisableBiometric: String,
    val btnSave: String, val btnCancel: String, val btnClose: String, val btnConfigure: String,
    val btnArchive: String, val btnActivate: String, val btnDeactivate: String,
    val btnAssociate: String, val btnDisassociate: String, val btnRevert: String,
    val titleNewPerson: String, val titleEditProfile: String,
    val hintChildName: String, val hintBirthDate: String, val hintSchoolYear: String,
    val labelProfilePhoto: String, val btnChoosePhoto: String,
    val noPhotoSelected: String, val photoSet: String,
    val titlePhotoSource: String, val optCamera: String, val optGallery: String,
    val titleNewActivity: String, val hintActivityName: String, val labelPeriodicity2: String,
    val titleNewMission: String, val subtitleNewMission: String,
    val labelMissionData: String, val hintMissionName: String, val hintRewardPoints: String,
    val labelParticipantsReceive: String, val labelPhases: String,
    val hintPhaseName: String, val btnAddPhaseInDialog: String,
    val orGenerateAuto: String, val hintPhaseCount: String, val btnGeneratePhases: String,
    val noPhasesAdded: String, val btnRemove: String,
    val titleNewMovement: String, val titleMoveBalance: String,
    val labelPerson: String, val labelType: String, val labelUnit: String,
    val unitPoints: String, val unitBRL: String,
    val hintAmountPoints: String, val hintAmountBRL: String,
    val optAddBalance: String, val optWithdraw: String, val optPenalize: String,
    val titleDailyAllowance: String, val labelAmountPerDay: String,
    val titlePointValue: String, val hintPointValue: String, val notePointValue: String,
    val labelCalendar: String, val labelStartsAt: String, val weekDays: List<String>,
    val toastInformName: String, val toastRegisterTwo: String,
    val toastNoPeopleAvailable: String, val toastSequenceInverted: String,
    val toastRewardCredited: String, val toastPhotoUpdated: String,
    val toastCameraDenied: String, val toastMissionDeleted: String,
    val toastPenaltyReverted: String, val toastBackupExported: String,
    val toastBackupRestored: String, val toastAmountGreaterZero: String,
    val toastInformReason: String, val toastInformAmount: String,
    val toastMissionConcluded: String, val toastAllPhases: String,
    val toastNoParticipants: String, val toastNextEvent: String,
    val confirmDeleteMission: String, val confirmReversePenalty: String,
    val typeDeposit: String, val typeWithdraw: String, val typePenalty: String, val typeDailyAllowance: String,
    val periodicityDaily: String, val periodicityWeekly: String, val periodicityMonthly: String,
    val reversalPrefix: String, val phaseTemplate: String,
    val nameLabel: String,
)

object AppStrings {
    val pt = Lang(
        tabToday = "Início", tabFamily = "Família", tabTasks = "Tarefas",
        tabMissions = "Missões", tabBalance = "Saldo", tabConfig = "Config",
        headerSubtitle = "Tarefas & Recompensas ⭐",
        sectionToday = "Hoje", noActiveTasks = "Nenhuma atividade ativa ainda.",
        labelNow = "Agora", labelPeriodicity = "Periodicidade: ",
        labelNextChange = "Próxima alternância: ", btnSwapTasks = "Trocar próximas tarefas",
        noPersonAssigned = "Sem pessoa",
        sectionFamily = "Família", noPeople = "Nenhuma pessoa cadastrada.", yearsOld = "anos",
        sectionTasks = "Atividades", labelOrder = "Ordem: ", labelNextEvent = "Próximo evento: ",
        labelManualAdjust = "Ajuste manual aplicado: ",
        btnAssociatePerson = "Associar pessoa", btnRemovePerson = "Desassociar pessoa",
        sectionMissions = "Missões", noMissions = "Nenhuma missão cadastrada.",
        labelRewardPerParticipant = "Recompensa: %s pontos para cada participante",
        labelParticipants = "Participantes: ", noPhases = "Sem fases ainda.",
        noParticipants = "Sem participantes", statusCompleted = "Concluída",
        statusReady = "Pronta para concluir", statusInProgress = "Em andamento",
        btnAddPhase = "Adicionar fase", btnCompleteCredit = "Concluir e creditar",
        btnDeleteMission = "Excluir missão",
        sectionRewards = "Recompensas", labelBalance = "Saldo: %s pontos",
        tapForStatement = "Toque para ver o extrato completo",
        btnAddBalance = "Adicionar saldo", btnWithdraw = "Saque", btnPenalize = "Penalizar",
        titleStatement = "Extrato", labelCurrentBalance = "Saldo atual",
        labelMovements = "Movimentações", noMovements = "Nenhuma movimentação ainda",
        btnReversePenalty = "Reverter penalidade", labelReversed = "Estornada",
        sectionConfig = "Configurações",
        cardPointValue = "Valor do ponto", pointValueDesc = "1 ponto = %s",
        cardDailyAllowance = "Mesada diária", statusDisabled = "Desativada",
        statusEnabledSince = "Ativa desde %s · %d pontos/dia",
        cardBackup = "Backup local",
        backupDesc = "Exporte um arquivo JSON e copie para outro aparelho. Ao importar, os dados atuais são substituídos pelo arquivo escolhido.",
        btnGenerateBackup = "Gerar arquivo de backup", btnRestoreBackup = "Restaurar de arquivo",
        cardSummary = "Resumo", labelPeople = "%d pessoas",
        labelActivities = "%d atividades", labelTransactions = "%d movimentações",
        cardLanguage = "Idioma", titleLanguage = "Escolher idioma",
        cardBiometric = "Biometria", biometricOn = "Ativada", biometricOff = "Desativada",
        biometricTitle = "Autenticação necessária",
        biometricSubtitle = "Use sua digital para acessar o app",
        biometricCancel = "Sair",
        biometricNotAvailable = "Biometria não disponível (requer Android 9+).",
        btnEnableBiometric = "Ativar biometria", btnDisableBiometric = "Desativar biometria",
        btnSave = "Salvar", btnCancel = "Cancelar", btnClose = "Fechar",
        btnConfigure = "Configurar", btnArchive = "Arquivar",
        btnActivate = "Ativar", btnDeactivate = "Desativar",
        btnAssociate = "Associar", btnDisassociate = "Desassociar", btnRevert = "Reverter",
        titleNewPerson = "Nova pessoa", titleEditProfile = "Perfil — %s",
        hintChildName = "Nome da criança", hintBirthDate = "Data de nascimento (dd/mm/aaaa)",
        hintSchoolYear = "Escolaridade (ex: 3º ano do Fundamental)",
        labelProfilePhoto = "Foto de perfil", btnChoosePhoto = "📷  Escolher foto",
        noPhotoSelected = "Nenhuma foto selecionada", photoSet = "✓ Foto definida",
        titlePhotoSource = "Escolher foto", optCamera = "Tirar foto com câmera",
        optGallery = "Escolher da galeria",
        titleNewActivity = "Nova atividade", hintActivityName = "Ex: Tomar banho, Arrumar o quarto...",
        labelPeriodicity2 = "Periodicidade",
        titleNewMission = "Nova missão", subtitleNewMission = "Defina participantes, recompensa e etapas.",
        labelMissionData = "Dados da missão", hintMissionName = "Nome da missão",
        hintRewardPoints = "Valor em pontos por participante",
        labelParticipantsReceive = "Participantes que recebem",
        labelPhases = "Etapas", hintPhaseName = "Nome da etapa",
        btnAddPhaseInDialog = "Adicionar etapa", orGenerateAuto = "Ou gere automaticamente",
        hintPhaseCount = "Quantidade de etapas", btnGeneratePhases = "Gerar etapas",
        noPhasesAdded = "Nenhuma etapa adicionada.", btnRemove = "Remover",
        titleNewMovement = "Nova movimentação", titleMoveBalance = "Movimentar saldo",
        labelPerson = "Pessoa", labelType = "Tipo", labelUnit = "Unidade",
        unitPoints = "Pontos", unitBRL = "Reais (R$)",
        hintAmountPoints = "Quantidade de pontos", hintAmountBRL = "Valor em reais (ex: 1.50)",
        optAddBalance = "Adicionar saldo", optWithdraw = "Executar saque",
        optPenalize = "Remover por penalidade",
        titleDailyAllowance = "Mesada diária", labelAmountPerDay = "Valor por dia (pontos)",
        titlePointValue = "Valor do ponto", hintPointValue = "Ex: 0.33",
        notePointValue = "Use ponto como separador decimal. Ex: 0.33 = R$ 0,33",
        labelCalendar = "Calendário da atividade", labelStartsAt = "Começa em %s",
        weekDays = listOf("Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"),
        toastInformName = "Informe um nome.", toastRegisterTwo = "Cadastre pelo menos duas pessoas.",
        toastNoPeopleAvailable = "Não há pessoas disponíveis para associar.",
        toastSequenceInverted = "Sequência invertida para os próximos períodos.",
        toastRewardCredited = "Recompensa creditada.", toastPhotoUpdated = "Foto atualizada!",
        toastCameraDenied = "Permissão de câmera negada.", toastMissionDeleted = "Missão excluída.",
        toastPenaltyReverted = "Penalidade estornada.", toastBackupExported = "Backup exportado.",
        toastBackupRestored = "Backup restaurado.",
        toastAmountGreaterZero = "O valor precisa ser maior que zero.",
        toastInformReason = "Informe um motivo.", toastInformAmount = "Informe um valor válido.",
        toastMissionConcluded = "Missão já concluída.", toastAllPhases = "Marque todas as fases antes de concluir.",
        toastNoParticipants = "A missão não tem participantes.",
        toastNextEvent = "%s será o próximo evento.",
        confirmDeleteMission = "Deseja excluir \"%s\"? Esta ação não pode ser desfeita.",
        confirmReversePenalty = "Devolver %s pontos para %s?\n\n\"%s\"",
        typeDeposit = "Depósito", typeWithdraw = "Saque", typePenalty = "Penalidade",
        typeDailyAllowance = "Mesada diária",
        periodicityDaily = "Diária", periodicityWeekly = "Semanal", periodicityMonthly = "Mensal",
        reversalPrefix = "Estorno: ", phaseTemplate = "Etapa %d/%d",
        nameLabel = "Nome *",
    )

    val es = Lang(
        tabToday = "Inicio", tabFamily = "Familia", tabTasks = "Tareas",
        tabMissions = "Misiones", tabBalance = "Saldo", tabConfig = "Config",
        headerSubtitle = "Tareas & Recompensas ⭐",
        sectionToday = "Hoy", noActiveTasks = "Sin actividades activas aún.",
        labelNow = "Ahora", labelPeriodicity = "Periodicidad: ",
        labelNextChange = "Próximo cambio: ", btnSwapTasks = "Intercambiar próximas tareas",
        noPersonAssigned = "Sin persona",
        sectionFamily = "Familia", noPeople = "Ninguna persona registrada.", yearsOld = "años",
        sectionTasks = "Actividades", labelOrder = "Orden: ", labelNextEvent = "Próximo evento: ",
        labelManualAdjust = "Ajuste manual aplicado: ",
        btnAssociatePerson = "Asociar persona", btnRemovePerson = "Desasociar persona",
        sectionMissions = "Misiones", noMissions = "Ninguna misión registrada.",
        labelRewardPerParticipant = "Recompensa: %s puntos por participante",
        labelParticipants = "Participantes: ", noPhases = "Sin etapas aún.",
        noParticipants = "Sin participantes", statusCompleted = "Completada",
        statusReady = "Lista para completar", statusInProgress = "En progreso",
        btnAddPhase = "Agregar etapa", btnCompleteCredit = "Completar y acreditar",
        btnDeleteMission = "Eliminar misión",
        sectionRewards = "Recompensas", labelBalance = "Saldo: %s puntos",
        tapForStatement = "Toque para ver el extracto completo",
        btnAddBalance = "Agregar saldo", btnWithdraw = "Retiro", btnPenalize = "Penalizar",
        titleStatement = "Extracto", labelCurrentBalance = "Saldo actual",
        labelMovements = "Movimientos", noMovements = "Sin movimientos aún",
        btnReversePenalty = "Revertir penalidad", labelReversed = "Revertida",
        sectionConfig = "Configuración",
        cardPointValue = "Valor del punto", pointValueDesc = "1 punto = %s",
        cardDailyAllowance = "Mesada diaria", statusDisabled = "Desactivada",
        statusEnabledSince = "Activa desde %s · %d puntos/día",
        cardBackup = "Copia de seguridad",
        backupDesc = "Exporte un archivo JSON y cópielo a otro dispositivo. Al importar, los datos actuales se reemplazan.",
        btnGenerateBackup = "Generar copia de seguridad", btnRestoreBackup = "Restaurar desde archivo",
        cardSummary = "Resumen", labelPeople = "%d personas",
        labelActivities = "%d actividades", labelTransactions = "%d movimientos",
        cardLanguage = "Idioma", titleLanguage = "Elegir idioma",
        cardBiometric = "Biometría", biometricOn = "Activada", biometricOff = "Desactivada",
        biometricTitle = "Autenticación requerida",
        biometricSubtitle = "Use su huella para acceder a la app",
        biometricCancel = "Salir",
        biometricNotAvailable = "Biometría no disponible (requiere Android 9+).",
        btnEnableBiometric = "Activar biometría", btnDisableBiometric = "Desactivar biometría",
        btnSave = "Guardar", btnCancel = "Cancelar", btnClose = "Cerrar",
        btnConfigure = "Configurar", btnArchive = "Archivar",
        btnActivate = "Activar", btnDeactivate = "Desactivar",
        btnAssociate = "Asociar", btnDisassociate = "Desasociar", btnRevert = "Revertir",
        titleNewPerson = "Nueva persona", titleEditProfile = "Perfil — %s",
        hintChildName = "Nombre del niño", hintBirthDate = "Fecha de nacimiento (dd/mm/aaaa)",
        hintSchoolYear = "Escolaridad (ej: 3er grado)",
        labelProfilePhoto = "Foto de perfil", btnChoosePhoto = "📷  Elegir foto",
        noPhotoSelected = "Ninguna foto seleccionada", photoSet = "✓ Foto definida",
        titlePhotoSource = "Elegir foto", optCamera = "Tomar foto con cámara",
        optGallery = "Elegir de galería",
        titleNewActivity = "Nueva actividad", hintActivityName = "Ej: Ducharse, Ordenar el cuarto...",
        labelPeriodicity2 = "Periodicidad",
        titleNewMission = "Nueva misión", subtitleNewMission = "Define participantes, recompensa y etapas.",
        labelMissionData = "Datos de la misión", hintMissionName = "Nombre de la misión",
        hintRewardPoints = "Valor en puntos por participante",
        labelParticipantsReceive = "Participantes que reciben",
        labelPhases = "Etapas", hintPhaseName = "Nombre de la etapa",
        btnAddPhaseInDialog = "Agregar etapa", orGenerateAuto = "O generar automáticamente",
        hintPhaseCount = "Cantidad de etapas", btnGeneratePhases = "Generar etapas",
        noPhasesAdded = "Ninguna etapa agregada.", btnRemove = "Eliminar",
        titleNewMovement = "Nuevo movimiento", titleMoveBalance = "Mover saldo",
        labelPerson = "Persona", labelType = "Tipo", labelUnit = "Unidad",
        unitPoints = "Puntos", unitBRL = "Reales (R$)",
        hintAmountPoints = "Cantidad de puntos", hintAmountBRL = "Valor en reales (ej: 1.50)",
        optAddBalance = "Agregar saldo", optWithdraw = "Ejecutar retiro",
        optPenalize = "Quitar por penalidad",
        titleDailyAllowance = "Mesada diaria", labelAmountPerDay = "Valor por día (puntos)",
        titlePointValue = "Valor del punto", hintPointValue = "Ej: 0.33",
        notePointValue = "Use punto como separador decimal. Ej: 0.33 = R$ 0,33",
        labelCalendar = "Calendario de la actividad", labelStartsAt = "Empieza el %s",
        weekDays = listOf("Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"),
        toastInformName = "Informe un nombre.", toastRegisterTwo = "Registre al menos dos personas.",
        toastNoPeopleAvailable = "No hay personas disponibles para asociar.",
        toastSequenceInverted = "Secuencia invertida para los próximos períodos.",
        toastRewardCredited = "Recompensa acreditada.", toastPhotoUpdated = "¡Foto actualizada!",
        toastCameraDenied = "Permiso de cámara denegado.", toastMissionDeleted = "Misión eliminada.",
        toastPenaltyReverted = "Penalidad revertida.", toastBackupExported = "Copia exportada.",
        toastBackupRestored = "Copia restaurada.",
        toastAmountGreaterZero = "El valor debe ser mayor que cero.",
        toastInformReason = "Informe un motivo.", toastInformAmount = "Informe un valor válido.",
        toastMissionConcluded = "Misión ya completada.", toastAllPhases = "Marque todas las etapas antes de completar.",
        toastNoParticipants = "La misión no tiene participantes.",
        toastNextEvent = "%s será el próximo evento.",
        confirmDeleteMission = "¿Eliminar \"%s\"? Esta acción no se puede deshacer.",
        confirmReversePenalty = "¿Devolver %s puntos a %s?\n\n\"%s\"",
        typeDeposit = "Depósito", typeWithdraw = "Retiro", typePenalty = "Penalidad",
        typeDailyAllowance = "Mesada diaria",
        periodicityDaily = "Diaria", periodicityWeekly = "Semanal", periodicityMonthly = "Mensual",
        reversalPrefix = "Reembolso: ", phaseTemplate = "Etapa %d/%d",
        nameLabel = "Nombre *",
    )

    val en = Lang(
        tabToday = "Today", tabFamily = "Family", tabTasks = "Tasks",
        tabMissions = "Missions", tabBalance = "Balance", tabConfig = "Config",
        headerSubtitle = "Tasks & Rewards ⭐",
        sectionToday = "Today", noActiveTasks = "No active activities yet.",
        labelNow = "Now", labelPeriodicity = "Periodicity: ",
        labelNextChange = "Next change: ", btnSwapTasks = "Swap next tasks",
        noPersonAssigned = "No person",
        sectionFamily = "Family", noPeople = "No people registered.", yearsOld = "years old",
        sectionTasks = "Activities", labelOrder = "Order: ", labelNextEvent = "Next event: ",
        labelManualAdjust = "Manual adjustment applied: ",
        btnAssociatePerson = "Associate person", btnRemovePerson = "Remove person",
        sectionMissions = "Missions", noMissions = "No missions registered.",
        labelRewardPerParticipant = "Reward: %s points per participant",
        labelParticipants = "Participants: ", noPhases = "No phases yet.",
        noParticipants = "No participants", statusCompleted = "Completed",
        statusReady = "Ready to complete", statusInProgress = "In progress",
        btnAddPhase = "Add phase", btnCompleteCredit = "Complete and credit",
        btnDeleteMission = "Delete mission",
        sectionRewards = "Rewards", labelBalance = "Balance: %s points",
        tapForStatement = "Tap to see full statement",
        btnAddBalance = "Add balance", btnWithdraw = "Withdraw", btnPenalize = "Penalize",
        titleStatement = "Statement", labelCurrentBalance = "Current balance",
        labelMovements = "Movements", noMovements = "No movements yet",
        btnReversePenalty = "Reverse penalty", labelReversed = "Reversed",
        sectionConfig = "Settings",
        cardPointValue = "Point value", pointValueDesc = "1 point = %s",
        cardDailyAllowance = "Daily allowance", statusDisabled = "Disabled",
        statusEnabledSince = "Active since %s · %d points/day",
        cardBackup = "Local backup",
        backupDesc = "Export a JSON file and copy to another device. When importing, current data is replaced by the chosen file.",
        btnGenerateBackup = "Generate backup", btnRestoreBackup = "Restore from file",
        cardSummary = "Summary", labelPeople = "%d people",
        labelActivities = "%d activities", labelTransactions = "%d transactions",
        cardLanguage = "Language", titleLanguage = "Choose language",
        cardBiometric = "Biometrics", biometricOn = "Enabled", biometricOff = "Disabled",
        biometricTitle = "Authentication required",
        biometricSubtitle = "Use your fingerprint to access the app",
        biometricCancel = "Exit",
        biometricNotAvailable = "Biometrics not available (requires Android 9+).",
        btnEnableBiometric = "Enable biometrics", btnDisableBiometric = "Disable biometrics",
        btnSave = "Save", btnCancel = "Cancel", btnClose = "Close",
        btnConfigure = "Configure", btnArchive = "Archive",
        btnActivate = "Activate", btnDeactivate = "Deactivate",
        btnAssociate = "Associate", btnDisassociate = "Remove", btnRevert = "Reverse",
        titleNewPerson = "New person", titleEditProfile = "Profile — %s",
        hintChildName = "Child's name", hintBirthDate = "Birth date (dd/mm/yyyy)",
        hintSchoolYear = "School year (e.g.: 3rd grade)",
        labelProfilePhoto = "Profile photo", btnChoosePhoto = "📷  Choose photo",
        noPhotoSelected = "No photo selected", photoSet = "✓ Photo set",
        titlePhotoSource = "Choose photo", optCamera = "Take photo with camera",
        optGallery = "Choose from gallery",
        titleNewActivity = "New activity", hintActivityName = "E.g.: Take a shower, Tidy the room...",
        labelPeriodicity2 = "Periodicity",
        titleNewMission = "New mission", subtitleNewMission = "Define participants, reward and phases.",
        labelMissionData = "Mission data", hintMissionName = "Mission name",
        hintRewardPoints = "Value in points per participant",
        labelParticipantsReceive = "Participants who receive",
        labelPhases = "Phases", hintPhaseName = "Phase name",
        btnAddPhaseInDialog = "Add phase", orGenerateAuto = "Or generate automatically",
        hintPhaseCount = "Number of phases", btnGeneratePhases = "Generate phases",
        noPhasesAdded = "No phases added.", btnRemove = "Remove",
        titleNewMovement = "New movement", titleMoveBalance = "Move balance",
        labelPerson = "Person", labelType = "Type", labelUnit = "Unit",
        unitPoints = "Points", unitBRL = "BRL (R$)",
        hintAmountPoints = "Number of points", hintAmountBRL = "Value in BRL (e.g.: 1.50)",
        optAddBalance = "Add balance", optWithdraw = "Execute withdrawal",
        optPenalize = "Remove as penalty",
        titleDailyAllowance = "Daily allowance", labelAmountPerDay = "Amount per day (points)",
        titlePointValue = "Point value", hintPointValue = "E.g.: 0.33",
        notePointValue = "Use period as decimal separator. E.g.: 0.33 = R$ 0.33",
        labelCalendar = "Activity calendar", labelStartsAt = "Starts at %s",
        weekDays = listOf("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
        toastInformName = "Enter a name.", toastRegisterTwo = "Register at least two people.",
        toastNoPeopleAvailable = "No people available to associate.",
        toastSequenceInverted = "Sequence inverted for next periods.",
        toastRewardCredited = "Reward credited.", toastPhotoUpdated = "Photo updated!",
        toastCameraDenied = "Camera permission denied.", toastMissionDeleted = "Mission deleted.",
        toastPenaltyReverted = "Penalty reversed.", toastBackupExported = "Backup exported.",
        toastBackupRestored = "Backup restored.",
        toastAmountGreaterZero = "Amount must be greater than zero.",
        toastInformReason = "Enter a reason.", toastInformAmount = "Enter a valid amount.",
        toastMissionConcluded = "Mission already completed.", toastAllPhases = "Mark all phases before completing.",
        toastNoParticipants = "The mission has no participants.",
        toastNextEvent = "%s will be the next event.",
        confirmDeleteMission = "Delete \"%s\"? This action cannot be undone.",
        confirmReversePenalty = "Return %s points to %s?\n\n\"%s\"",
        typeDeposit = "Deposit", typeWithdraw = "Withdrawal", typePenalty = "Penalty",
        typeDailyAllowance = "Daily allowance",
        periodicityDaily = "Daily", periodicityWeekly = "Weekly", periodicityMonthly = "Monthly",
        reversalPrefix = "Reversal: ", phaseTemplate = "Phase %d/%d",
        nameLabel = "Name *",
    )

    fun get(language: String): Lang = when (language) {
        "es" -> es
        "en" -> en
        else -> pt
    }
}
